name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wmcg/washing-machine-alerter:test, wmcg/washing-machine-alerter:buildcache
          cache-from: type=registry,ref=wmcg/washing-machine-alerter:buildcache
          cache-to: type=registry,ref=wmcg/washing-machine-alerter:buildcache,mode=max

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gh-action-wm

      - name: Deploy
        run: ssh -o StrictHostKeyChecking=no root@mega-pi '/root/services/washing-machine-alerter/deploy.sh'